---
- name: Add homelab users to server os
  hosts: all
  become: true
  tasks:
    - name: Add homelab users ansible, ghactions
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        - ansible
        - ghactions
    - name: Add homelab users with sudo group alexander
      ansible.builtin.user:
        name: "{{ item }}"
        groups: sudo
      loop:
        - alexander
