---
- name: play for updating cache and installing essential packages
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and make sure gpg, fish and neofetch are installed
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
      loop:
        - fish
        - neofetch
        - gpg