# .github/workflows/ansible-lint.yml
name: "ansible lint"

run-name: ansible lint |  ${{ github.ref }}

on:
  push:
    branches:
      - main
    paths:
      - 'playbooks/**'
  workflow_dispatch:

jobs:
  build:
    name: ansible lint |  ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
